const TOPICS = [ // List of topics to choose from
  { label: "Apple", value: "Apple" },
  { label: "Google", value: "Google" },
  { label: "Artificial Intelligence", value: "artificial intelligence" },
  { label: "Cybersecurity", value: "cybersecurity" },
  { label: "Electric Vehicles", value: "electric vehicles" },
  { label: "Climate Change", value: "climate change" },
  { label: "Ukraine War", value: "Ukraine war" },
  { label: "United Nations", value: "United Nations" },
  { label: "Immigration", value: "immigration" },
  { label: "Human Rights", value: "human rights" },
  { label: "Inflation", value: "inflation" },
  { label: "Stock Market", value: "stock market" },
  { label: "Bitcoin", value: "Bitcoin" },
  { label: "Oil Prices", value: "oil prices" },
  { label: "Trade War", value: "trade war" },
  { label: "Federal Reserve", value: "Federal Reserve" },
  { label: "NASA", value: "NASA" },
  { label: "Space Exploration", value: "space exploration" },
  { label: "Cancer Research", value: "cancer research" },
  { label: "Earthquake", value: "earthquake" },
  { label: "Pandemic", value: "pandemic" },
  { label: "FIFA World Cup", value: "FIFA World Cup" },
  { label: "Olympics", value: "Olympics" },
  { label: "Formula 1", value: "Formula 1" },
  { label: "NBA", value: "NBA" },
  { label: "Tennis", value: "tennis" },
  { label: "Hollywood", value: "Hollywood" },
  { label: "Netflix", value: "Netflix" },
  { label: "Grammy Awards", value: "Grammy Awards" },
  { label: "Video Games", value: "video games" },
];
